remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: /Delphi-Playground

# --- Banner Content ---
title: Delphi Playground
description: Modern architectural patterns, techniques, and best practices for Object Pascal developers. From Fluent Helpers to Lock-Free Atomic Wrappers.

# --- Optional: GitHub Buttons ---
# This removes the "View on GitHub" and "Download" buttons to the banner
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/tregubovav-dev/Delphi-Playground